version: '3.9'
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_mannaportal
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  node_express:
    container_name: backend
    build: ./backend
    environment:
      - HOST=postgres
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - postgres

  node_react:
    container_name: frontend
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - node_express
volumes:
  db:
    driver: local