version: "3.9" 
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_mannaportal
    ports:
      - "3307:3306"
  web:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"