version: "3.9" 
services:
  mariadb:
    container_name: mdb
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=Password123!
  web:
    build: .
    restart: always
    depends_on:
      - mariadb
    ports:
      - "80:80"
