CREATE TABLE IF NOT EXISTS db_teste.imagens (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nm_imagem VARCHAR(100) NOT NULL,
	dt_created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	dt_update TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
